// FAQ content data for programmatic SEO pages
export interface FAQ {
  slug: string;
  question: string;
  answer: string;
  keywords: string[];
  relatedQuestions?: string[];
}

export const faqs: FAQ[] = [
  {
    slug: 'what-is-akowe',
    question: 'What is Akowe?',
    answer: 'Akowe is an all-in-one academic writing platform designed for students and researchers. It combines AI writing assistance with real source search, automatic citation formatting, and plagiarism detection—all in one workspace. Unlike generic AI tools, Akowe is built specifically for academic work with proper citations and academic integrity in mind.',
    keywords: [
      'what is akowe',
      'akowe academic writing tool',
      'akowe platform',
      'akowe features',
      'academic writing software',
    ],
    relatedQuestions: [
      'how does akowe work',
      'is akowe free',
      'akowe vs other tools',
    ],
  },
  {
    slug: 'how-does-akowe-work',
    question: 'How does Akowe work?',
    answer: 'Akowe provides a unified workspace for academic writing. You can search real academic sources from OpenAlex and Crossref databases, add citations to your paper with one click, and get AI writing assistance that understands your project context. Akowe automatically formats citations in any style (APA, MLA, Chicago, etc.) and includes built-in plagiarism detection. Everything is integrated—no need to switch between multiple tools.',
    keywords: [
      'how does akowe work',
      'akowe tutorial',
      'using akowe',
      'akowe guide',
      'akowe how to',
    ],
  },
  {
    slug: 'is-akowe-free',
    question: 'Is Akowe free?',
    answer: 'Akowe offers a free tier to get started. You can create projects, search sources, add citations, and use basic AI writing features at no cost. Premium plans unlock advanced features like unlimited AI usage, priority support, and advanced plagiarism checking. You can upgrade when you need more features.',
    keywords: [
      'is akowe free',
      'akowe pricing',
      'akowe cost',
      'free academic writing tool',
      'akowe free trial',
    ],
  },
  {
    slug: 'what-citation-styles-does-akowe-support',
    question: 'What citation styles does Akowe support?',
    answer: 'Akowe supports all major citation styles including APA (7th edition), MLA (9th edition), Chicago (17th edition), IEEE, Harvard, Vancouver, ACS, and AMA. You can switch between styles at any time, and Akowe will automatically reformat all your citations. This makes it easy to adapt your paper for different journals or assignments.',
    keywords: [
      'akowe citation styles',
      'akowe APA MLA',
      'citation styles supported',
      'akowe citation formats',
      'academic citation styles',
    ],
  },
  {
    slug: 'does-akowe-check-for-plagiarism',
    question: 'Does Akowe check for plagiarism?',
    answer: 'Yes, Akowe includes built-in plagiarism detection. You can check your entire paper or specific sections before submission. Akowe identifies potential plagiarism and provides detailed reports showing similarity percentages and sources. This helps you catch unintentional plagiarism and ensure academic integrity.',
    keywords: [
      'akowe plagiarism checker',
      'plagiarism detection akowe',
      'akowe plagiarism check',
      'academic plagiarism checker',
      'plagiarism tool',
    ],
  },
  {
    slug: 'can-i-use-akowe-for-my-thesis',
    question: 'Can I use Akowe for my thesis or dissertation?',
    answer: 'Absolutely! Akowe is designed for long-form academic writing including theses, dissertations, and research papers. The platform supports multiple sections, chapter organization, and can handle large documents. You can manage hundreds of citations across your entire thesis, and Akowe maintains consistency throughout.',
    keywords: [
      'akowe thesis',
      'akowe dissertation',
      'thesis writing tool',
      'dissertation software',
      'thesis citation manager',
    ],
  },
  {
    slug: 'how-is-akowe-different-from-chatgpt',
    question: 'How is Akowe different from ChatGPT?',
    answer: 'Unlike ChatGPT, Akowe is built specifically for academic work. ChatGPT often produces generic text and can hallucinate citations. Akowe searches real academic sources from OpenAlex and Crossref, formats citations correctly, and understands your project context. It maintains academic integrity and provides proper citations—not fake ones. Akowe is a writing assistant, not a replacement for your work.',
    keywords: [
      'akowe vs chatgpt',
      'akowe vs ai tools',
      'academic ai vs chatgpt',
      'akowe comparison',
      'best academic writing tool',
    ],
  },
  {
    slug: 'can-i-export-my-paper-from-akowe',
    question: 'Can I export my paper from Akowe?',
    answer: 'Yes, you can export your papers from Akowe in multiple formats including Word (.docx), PDF, and LaTeX. Your citations and bibliography are automatically formatted according to your chosen citation style. You can also copy your work to other platforms if needed.',
    keywords: [
      'akowe export',
      'export paper akowe',
      'akowe download',
      'akowe word export',
      'akowe pdf export',
    ],
  },
  {
    slug: 'does-akowe-work-offline',
    question: 'Does Akowe work offline?',
    answer: 'Akowe is a web-based platform that requires an internet connection for most features, including source search, AI assistance, and citation formatting. However, you can continue writing offline, and your work is automatically saved. When you reconnect, all features become available again.',
    keywords: [
      'akowe offline',
      'akowe internet required',
      'akowe online tool',
      'akowe cloud',
      'akowe sync',
    ],
  },
  {
    slug: 'is-my-work-secure-on-akowe',
    question: 'Is my work secure on Akowe?',
    answer: 'Yes, Akowe takes security seriously. Your work is encrypted and stored securely. We never share your content with third parties, and you maintain full ownership of your work. Akowe complies with data protection regulations and academic privacy standards.',
    keywords: [
      'akowe security',
      'akowe privacy',
      'akowe data protection',
      'is akowe safe',
      'akowe secure',
    ],
  },
  {
    slug: 'can-i-collaborate-with-others-on-akowe',
    question: 'Can I collaborate with others on Akowe?',
    answer: 'Currently, Akowe focuses on individual writing projects. Each project belongs to one user. However, you can share exported documents with collaborators. Team collaboration features are planned for future updates.',
    keywords: [
      'akowe collaboration',
      'akowe team',
      'akowe sharing',
      'collaborative writing',
      'akowe group projects',
    ],
  },
  {
    slug: 'what-sources-does-akowe-search',
    question: 'What sources does Akowe search?',
    answer: 'Akowe searches real academic sources from OpenAlex and Crossref databases. These include peer-reviewed journal articles, books, conference papers, dissertations, and other scholarly materials. You can search by title, author, DOI, or keywords, and Akowe finds relevant academic sources—not generic web content.',
    keywords: [
      'akowe sources',
      'akowe database',
      'akowe academic sources',
      'akowe openalex',
      'akowe crossref',
    ],
  },
  {
    slug: 'how-accurate-are-akowe-citations',
    question: 'How accurate are Akowe citations?',
    answer: 'Akowe citations are highly accurate because they come from real academic databases (OpenAlex and Crossref). The platform automatically extracts citation information and formats it according to your chosen style. However, you should always review citations for accuracy, especially for unusual source types or edge cases.',
    keywords: [
      'akowe citation accuracy',
      'accurate citations',
      'akowe citation quality',
      'citation accuracy',
      'reliable citations',
    ],
  },
  {
    slug: 'can-i-import-citations-from-other-tools',
    question: 'Can I import citations from other tools like Zotero or Mendeley?',
    answer: 'Currently, Akowe doesn\'t support direct import from Zotero or Mendeley. However, you can manually add sources by searching in Akowe, or you can export your bibliography from other tools and use it as a reference. Import features are planned for future updates.',
    keywords: [
      'akowe import',
      'akowe zotero',
      'akowe mendeley',
      'import citations',
      'akowe migration',
    ],
  },
  {
    slug: 'does-akowe-support-latex',
    question: 'Does Akowe support LaTeX?',
    answer: 'Yes, Akowe supports LaTeX. You can export your papers in LaTeX format, and Akowe can help format citations in LaTeX syntax. The platform understands LaTeX commands and can assist with LaTeX-specific formatting needs.',
    keywords: [
      'akowe latex',
      'akowe latex support',
      'latex citations',
      'akowe latex export',
      'latex academic writing',
    ],
  },
  {
    slug: 'what-languages-does-akowe-support',
    question: 'What languages does Akowe support?',
    answer: 'Currently, Akowe primarily supports English-language academic writing. The interface is in English, and source search focuses on English-language academic databases. Support for other languages is planned for future updates.',
    keywords: [
      'akowe languages',
      'akowe multilingual',
      'akowe english',
      'language support',
      'akowe international',
    ],
  },
  {
    slug: 'how-much-does-akowe-cost',
    question: 'How much does Akowe cost?',
    answer: 'Akowe offers a free tier with basic features. Premium plans start at affordable monthly rates and unlock unlimited AI usage, advanced features, and priority support. Pricing is designed to be accessible for students and researchers. Check the pricing page for current rates.',
    keywords: [
      'akowe pricing',
      'akowe cost',
      'akowe subscription',
      'akowe plans',
      'akowe price',
    ],
  },
  {
    slug: 'can-i-cancel-my-akowe-subscription',
    question: 'Can I cancel my Akowe subscription?',
    answer: 'Yes, you can cancel your Akowe subscription at any time. There are no long-term contracts, and you can cancel from your account settings. Your subscription will remain active until the end of your billing period, and you\'ll retain access to premium features until then.',
    keywords: [
      'akowe cancel',
      'akowe subscription cancel',
      'cancel akowe',
      'akowe refund',
      'akowe billing',
    ],
  },
  {
    slug: 'does-akowe-have-a-mobile-app',
    question: 'Does Akowe have a mobile app?',
    answer: 'Currently, Akowe is a web-based platform optimized for desktop and tablet use. A mobile app is planned for future release. The web platform works well on mobile browsers, but the full experience is best on larger screens.',
    keywords: [
      'akowe mobile',
      'akowe app',
      'akowe ios',
      'akowe android',
      'akowe mobile app',
    ],
  },
  {
    slug: 'what-is-the-difference-between-akowe-and-jenni',
    question: 'What is the difference between Akowe and Jenni.ai?',
    answer: 'While both are AI writing tools, Akowe focuses specifically on academic writing with real sources and proper citations. Akowe searches actual academic databases (OpenAlex, Crossref) rather than generic web content, formats citations automatically in any style, and includes plagiarism detection. Akowe is designed for serious academic work, not just content generation.',
    keywords: [
      'akowe vs jenni',
      'akowe vs jenni.ai',
      'akowe comparison',
      'jenni alternative',
      'academic writing tools',
    ],
  },
  {
    slug: 'can-akowe-help-with-research-paper-outline',
    question: 'Can Akowe help with research paper outlines?',
    answer: 'Yes, Akowe\'s AI assistant can help generate research paper outlines based on your topic, research question, and methodology. It understands academic paper structure and can suggest appropriate sections and organization. You can then expand each section with AI assistance and add citations as you write.',
    keywords: [
      'akowe outline',
      'research paper outline',
      'akowe paper structure',
      'outline generator',
      'academic outline',
    ],
  },
  {
    slug: 'does-akowe-work-with-google-docs',
    question: 'Does Akowe work with Google Docs?',
    answer: 'Akowe is a standalone platform with its own editor. You can\'t directly edit Google Docs within Akowe, but you can export your work from Akowe to Word format and then import it into Google Docs. Alternatively, you can write in Akowe and export when finished.',
    keywords: [
      'akowe google docs',
      'akowe integration',
      'akowe word',
      'akowe export',
      'akowe compatibility',
    ],
  },
  {
    slug: 'how-do-i-cite-sources-in-akowe',
    question: 'How do I cite sources in Akowe?',
    answer: 'Citing sources in Akowe is simple: search for sources using the citation search feature, select the source you want to cite, choose where to insert it in your paper, and Akowe automatically formats it according to your chosen citation style. You can add in-text citations and build your bibliography automatically.',
    keywords: [
      'how to cite in akowe',
      'akowe citations',
      'adding citations',
      'akowe citation guide',
      'cite sources akowe',
    ],
  },
  {
    slug: 'can-i-use-akowe-for-group-projects',
    question: 'Can I use Akowe for group projects?',
    answer: 'Currently, Akowe projects are individual. For group projects, each team member can use Akowe individually and then combine their work. Team collaboration features allowing shared projects and real-time collaboration are planned for future updates.',
    keywords: [
      'akowe group projects',
      'akowe collaboration',
      'akowe team',
      'group writing',
      'akowe sharing',
    ],
  },
  {
    slug: 'what-file-formats-can-i-upload-to-akowe',
    question: 'What file formats can I upload to Akowe?',
    answer: 'You can upload PDFs to Akowe for analysis and citation extraction. For writing, you start with a new project in Akowe\'s editor. You can also paste text from other sources. Support for importing Word documents and other formats is planned.',
    keywords: [
      'akowe upload',
      'akowe file formats',
      'akowe pdf',
      'akowe import',
      'akowe file support',
    ],
  },
  {
    slug: 'does-akowe-store-my-papers',
    question: 'Does Akowe store my papers?',
    answer: 'Yes, Akowe stores your papers securely in the cloud. This allows you to access your work from any device, and your work is automatically saved as you write. You maintain full ownership of your content, and you can delete projects at any time.',
    keywords: [
      'akowe storage',
      'akowe cloud',
      'akowe save',
      'akowe backup',
      'akowe data',
    ],
  },
  {
    slug: 'can-i-use-akowe-without-internet',
    question: 'Can I use Akowe without internet?',
    answer: 'Akowe requires an internet connection for most features including source search, AI assistance, and citation formatting. However, you can continue writing offline, and your work is saved locally. When you reconnect, everything syncs automatically.',
    keywords: [
      'akowe offline',
      'akowe internet',
      'akowe connection',
      'akowe online',
      'akowe sync',
    ],
  },
  {
    slug: 'how-do-i-change-citation-style-in-akowe',
    question: 'How do I change citation style in Akowe?',
    answer: 'You can change citation style at any time in your project settings. Simply select your desired style (APA, MLA, Chicago, etc.), and Akowe will automatically reformat all existing citations and your bibliography. This makes it easy to adapt your paper for different journals or assignments.',
    keywords: [
      'akowe citation style',
      'change citation style',
      'akowe APA MLA',
      'citation format',
      'akowe style settings',
    ],
  },
  {
    slug: 'does-akowe-support-footnotes',
    question: 'Does Akowe support footnotes?',
    answer: 'Yes, Akowe supports footnotes for citation styles that use them (like Chicago Notes-Bibliography style). You can add footnotes, and Akowe will format them correctly according to your chosen citation style.',
    keywords: [
      'akowe footnotes',
      'footnote citations',
      'akowe chicago',
      'footnote support',
      'akowe notes',
    ],
  },
  {
    slug: 'can-i-cite-websites-in-akowe',
    question: 'Can I cite websites in Akowe?',
    answer: 'Yes, you can cite websites in Akowe. While Akowe focuses on academic sources from OpenAlex and Crossref, you can manually add website citations. Akowe will format them correctly according to your chosen citation style (APA, MLA, Chicago, etc.).',
    keywords: [
      'akowe website citation',
      'cite websites',
      'akowe web sources',
      'website citations',
      'akowe online sources',
    ],
  },
  {
    slug: 'what-is-akowe-ai-capable-of',
    question: 'What is Akowe AI capable of?',
    answer: 'Akowe\'s AI can help with writing assistance, generating outlines, improving clarity, suggesting research directions, and organizing ideas. It understands your project context, topic, and citation style. However, it\'s designed to assist your writing, not replace it. You maintain full control and academic integrity.',
    keywords: [
      'akowe AI',
      'akowe artificial intelligence',
      'akowe writing assistant',
      'akowe AI features',
      'akowe capabilities',
    ],
  },
  {
    slug: 'is-akowe-suitable-for-undergraduates',
    question: 'Is Akowe suitable for undergraduates?',
    answer: 'Absolutely! Akowe is designed for students at all levels, including undergraduates. It helps with research papers, essays, and assignments by providing real sources, proper citations, and writing assistance. The free tier is perfect for students getting started with academic writing.',
    keywords: [
      'akowe undergraduates',
      'akowe students',
      'akowe college',
      'student writing tool',
      'akowe university',
    ],
  },
  {
    slug: 'is-akowe-suitable-for-graduate-students',
    question: 'Is Akowe suitable for graduate students?',
    answer: 'Yes, Akowe is excellent for graduate students working on theses, dissertations, and research papers. It handles long-form writing, manages hundreds of citations, supports multiple citation styles, and includes features like plagiarism detection that are essential for graduate-level work.',
    keywords: [
      'akowe graduate students',
      'akowe thesis',
      'akowe dissertation',
      'graduate writing tool',
      'akowe research',
    ],
  },
  {
    slug: 'is-akowe-suitable-for-researchers',
    question: 'Is Akowe suitable for researchers and academics?',
    answer: 'Yes, Akowe is designed for researchers and academics. It searches real academic databases, formats citations for journal submissions, supports multiple citation styles, and helps maintain academic integrity. Researchers can use Akowe for papers, grant proposals, and other academic writing.',
    keywords: [
      'akowe researchers',
      'akowe academics',
      'akowe scholars',
      'research writing tool',
      'akowe professional',
    ],
  },
  {
    slug: 'how-do-i-get-started-with-akowe',
    question: 'How do I get started with Akowe?',
    answer: 'Getting started with Akowe is easy: sign up for a free account, create your first project, choose your citation style, and start writing. You can search for sources, add citations, and use AI assistance right away. No credit card required to start.',
    keywords: [
      'akowe get started',
      'akowe sign up',
      'akowe tutorial',
      'akowe beginner',
      'akowe start',
    ],
  },
  {
    slug: 'does-akowe-offer-student-discounts',
    question: 'Does Akowe offer student discounts?',
    answer: 'Akowe offers affordable pricing designed for students. The free tier provides access to core features, and premium plans are priced to be accessible for students. Check the pricing page for current student rates and any available discounts.',
    keywords: [
      'akowe student discount',
      'akowe student pricing',
      'akowe discount',
      'student pricing',
      'akowe affordable',
    ],
  },
  {
    slug: 'can-i-use-akowe-for-multiple-projects',
    question: 'Can I use Akowe for multiple projects?',
    answer: 'Yes, you can create and manage multiple projects in Akowe. Each project is separate with its own sources, citations, and settings. You can switch between projects easily and maintain different citation styles for different projects if needed.',
    keywords: [
      'akowe multiple projects',
      'akowe projects',
      'akowe workspace',
      'multiple papers',
      'akowe organization',
    ],
  },
  {
    slug: 'how-does-akowe-compare-to-mendeley',
    question: 'How does Akowe compare to Mendeley?',
    answer: 'Mendeley is primarily a reference manager, while Akowe is an all-in-one writing platform. Akowe combines citation management with AI writing assistance, source search, and plagiarism detection in one workspace. You don\'t need to switch between Mendeley and a writing tool—Akowe does both.',
    keywords: [
      'akowe vs mendeley',
      'akowe mendeley',
      'mendeley alternative',
      'akowe comparison',
      'reference manager',
    ],
  },
  {
    slug: 'how-does-akowe-compare-to-zotero',
    question: 'How does Akowe compare to Zotero?',
    answer: 'Zotero is a reference manager, while Akowe is a complete writing platform. Akowe includes citation management like Zotero, but also provides AI writing assistance, integrated source search, and plagiarism detection. Everything is in one place—no need to use Zotero plus a separate writing tool.',
    keywords: [
      'akowe vs zotero',
      'akowe zotero',
      'zotero alternative',
      'akowe comparison',
      'citation manager',
    ],
  },
  {
    slug: 'does-akowe-have-customer-support',
    question: 'Does Akowe have customer support?',
    answer: 'Yes, Akowe offers customer support via email. Premium users get priority support with faster response times. We also provide documentation, guides, and tutorials to help you get the most out of Akowe.',
    keywords: [
      'akowe support',
      'akowe help',
      'akowe customer service',
      'akowe contact',
      'akowe assistance',
    ],
  },
  {
    slug: 'can-i-try-akowe-before-paying',
    question: 'Can I try Akowe before paying?',
    answer: 'Yes! Akowe offers a free tier that lets you try all core features. You can create projects, search sources, add citations, and use basic AI features at no cost. No credit card required. Upgrade to premium when you need advanced features.',
    keywords: [
      'akowe free trial',
      'akowe try free',
      'akowe demo',
      'akowe test',
      'akowe free',
    ],
  },
  {
    slug: 'what-makes-akowe-better-than-other-tools',
    question: 'What makes Akowe better than other academic writing tools?',
    answer: 'Akowe combines multiple tools into one platform: real academic source search (not generic web), automatic citation formatting in any style, AI writing assistance designed for academics, and plagiarism detection. Unlike generic AI tools, Akowe understands academic context and maintains integrity. Unlike reference managers, Akowe includes writing assistance. It\'s the all-in-one solution.',
    keywords: [
      'akowe advantages',
      'akowe benefits',
      'akowe best',
      'akowe features',
      'why akowe',
    ],
  },
  {
    slug: 'does-akowe-work-on-mac',
    question: 'Does Akowe work on Mac?',
    answer: 'Yes, Akowe is a web-based platform that works on any device with a modern browser, including Mac computers. You can access Akowe from Safari, Chrome, Firefox, or any other modern browser on your Mac.',
    keywords: [
      'akowe mac',
      'akowe macbook',
      'akowe apple',
      'akowe safari',
      'akowe compatibility',
    ],
  },
  {
    slug: 'does-akowe-work-on-windows',
    question: 'Does Akowe work on Windows?',
    answer: 'Yes, Akowe is a web-based platform that works on any device with a modern browser, including Windows computers. You can access Akowe from Chrome, Edge, Firefox, or any other modern browser on Windows.',
    keywords: [
      'akowe windows',
      'akowe pc',
      'akowe chrome',
      'akowe edge',
      'akowe compatibility',
    ],
  },
  {
    slug: 'is-akowe-accurate',
    question: 'Is Akowe accurate?',
    answer: 'Akowe is designed for accuracy. It searches real academic databases (OpenAlex, Crossref) for sources, automatically formats citations according to official style guides, and provides AI assistance based on your actual project context. However, you should always review citations and content for accuracy, especially for edge cases.',
    keywords: [
      'akowe accuracy',
      'akowe reliable',
      'akowe quality',
      'is akowe accurate',
      'akowe precision',
    ],
  },
  {
    slug: 'can-i-use-akowe-for-commercial-research',
    question: 'Can I use Akowe for commercial research?',
    answer: 'Yes, Akowe can be used for commercial research projects. However, check the terms of service for any restrictions. Academic and personal use are fully supported, and commercial use may require a different license or plan.',
    keywords: [
      'akowe commercial',
      'akowe business',
      'akowe commercial use',
      'akowe license',
      'akowe terms',
    ],
  },
  {
    slug: 'does-akowe-have-an-api',
    question: 'Does Akowe have an API?',
    answer: 'Currently, Akowe does not have a public API. The platform is designed for direct use through the web interface. API access may be available in the future for enterprise customers.',
    keywords: [
      'akowe API',
      'akowe integration',
      'akowe developer',
      'akowe automation',
      'akowe API access',
    ],
  },
  {
    slug: 'how-often-is-akowe-updated',
    question: 'How often is Akowe updated?',
    answer: 'Akowe is actively developed and receives regular updates with new features, improvements, and bug fixes. Updates are released frequently to improve the platform and add new capabilities based on user feedback.',
    keywords: [
      'akowe updates',
      'akowe development',
      'akowe new features',
      'akowe improvements',
      'akowe roadmap',
    ],
  },
  {
    slug: 'how-do-i-change-my-akowe-password',
    question: 'How do I change my Akowe password?',
    answer: 'You can change your password from your account settings. Go to Settings, then Security, and follow the prompts to update your password. Make sure to use a strong, unique password.',
    keywords: ['akowe password', 'change password', 'akowe account security', 'password reset'],
  },
  {
    slug: 'can-i-use-akowe-on-multiple-devices',
    question: 'Can I use Akowe on multiple devices?',
    answer: 'Yes, Akowe is web-based and works on any device with a modern browser. Your work is synced across all devices, so you can start on your laptop and continue on your tablet or phone.',
    keywords: ['akowe multiple devices', 'akowe sync', 'akowe cross-device', 'akowe mobile'],
  },
  {
    slug: 'does-akowe-support-dark-mode',
    question: 'Does Akowe support dark mode?',
    answer: 'Akowe uses a system-aware theme that adapts to your device settings. The interface is designed to be comfortable for extended writing sessions.',
    keywords: ['akowe dark mode', 'akowe theme', 'akowe appearance'],
  },
  {
    slug: 'how-do-i-delete-my-akowe-account',
    question: 'How do I delete my Akowe account?',
    answer: 'You can delete your account from Settings. This will permanently delete all your projects and data. Make sure to export any work you want to keep before deleting your account.',
    keywords: ['akowe delete account', 'akowe account deletion', 'cancel akowe account'],
  },
  {
    slug: 'what-happens-to-my-data-if-i-cancel-akowe',
    question: 'What happens to my data if I cancel Akowe?',
    answer: 'Your data remains accessible even if you cancel your subscription. You can continue using the free tier with your existing projects. Only premium features are restricted.',
    keywords: ['akowe cancel', 'akowe data retention', 'akowe after cancellation'],
  },
  {
    slug: 'can-i-share-my-akowe-projects',
    question: 'Can I share my Akowe projects?',
    answer: 'Currently, projects are private to your account. You can export your work and share the exported files. Team collaboration features are planned for future updates.',
    keywords: ['akowe share', 'akowe collaboration', 'akowe export'],
  },
  {
    slug: 'does-akowe-work-with-screen-readers',
    question: 'Does Akowe work with screen readers?',
    answer: 'Akowe is designed to be accessible and works with screen readers. We continue to improve accessibility features based on user feedback.',
    keywords: ['akowe accessibility', 'akowe screen reader', 'akowe a11y'],
  },
  {
    slug: 'can-i-use-akowe-for-group-projects',
    question: 'Can I use Akowe for group projects?',
    answer: 'Currently, each team member can use Akowe individually and combine their work. Team collaboration features allowing shared projects are planned for future updates.',
    keywords: ['akowe group projects', 'akowe team', 'akowe collaboration'],
  },
  {
    slug: 'how-do-i-backup-my-akowe-work',
    question: 'How do I backup my Akowe work?',
    answer: 'Your work is automatically saved and synced to the cloud. You can also export your projects to Word or PDF format for additional backup. Your work is safe and accessible from any device.',
    keywords: ['akowe backup', 'akowe export', 'akowe save work'],
  },
  {
    slug: 'what-is-akowe-word-limit',
    question: 'What is the Akowe word limit?',
    answer: 'Akowe supports documents of any length. There\'s no hard word limit for your papers. The free tier has limits on AI usage per day, but you can write as much as you want.',
    keywords: ['akowe word limit', 'akowe document size', 'akowe paper length'],
  },
  {
    slug: 'can-i-import-documents-into-akowe',
    question: 'Can I import documents into Akowe?',
    answer: 'You can paste text from other sources into Akowe. PDF import for citation extraction is available. Full document import features are planned for future updates.',
    keywords: ['akowe import', 'akowe upload', 'akowe document import'],
  },
  {
    slug: 'does-akowe-have-grammar-checking',
    question: 'Does Akowe have grammar checking?',
    answer: 'Akowe\'s AI assistant can help improve your writing, including grammar and style suggestions. It\'s designed specifically for academic writing context.',
    keywords: ['akowe grammar', 'akowe grammar check', 'akowe writing help'],
  },
  {
    slug: 'can-i-use-akowe-offline',
    question: 'Can I use Akowe offline?',
    answer: 'Akowe requires an internet connection for most features. You can continue writing offline, and your work will sync when you reconnect. Full offline support is planned.',
    keywords: ['akowe offline', 'akowe internet required', 'akowe offline mode'],
  },
  {
    slug: 'how-do-i-contact-akowe-support',
    question: 'How do I contact Akowe support?',
    answer: 'You can contact Akowe support via email at ola@placeholderllc.name.ng. Premium users get priority support with faster response times.',
    keywords: ['akowe support', 'akowe contact', 'akowe help', 'akowe customer service'],
  },
  {
    slug: 'what-browsers-does-akowe-support',
    question: 'What browsers does Akowe support?',
    answer: 'Akowe works on all modern browsers including Chrome, Firefox, Safari, and Edge. We recommend using the latest version of your browser for the best experience.',
    keywords: ['akowe browsers', 'akowe compatibility', 'akowe browser support'],
  },
  {
    slug: 'does-akowe-have-keyboard-shortcuts',
    question: 'Does Akowe have keyboard shortcuts?',
    answer: 'Yes, Akowe supports keyboard shortcuts for common actions. Check the help menu or documentation for a complete list of shortcuts.',
    keywords: ['akowe shortcuts', 'akowe keyboard', 'akowe hotkeys'],
  },
  {
    slug: 'can-i-customize-akowe-interface',
    question: 'Can I customize the Akowe interface?',
    answer: 'Akowe\'s interface is designed for optimal academic writing. While full customization isn\'t available, the interface adapts to your device settings and preferences.',
    keywords: ['akowe customization', 'akowe interface', 'akowe settings'],
  },
  {
    slug: 'how-do-i-cite-multiple-sources-in-akowe',
    question: 'How do I cite multiple sources in Akowe?',
    answer: 'You can add multiple citations to your paper. Simply search for and add each source you want to cite. Akowe will format them all according to your chosen citation style.',
    keywords: ['akowe multiple citations', 'akowe cite sources', 'akowe bibliography'],
  },
  {
    slug: 'does-akowe-support-footnotes',
    question: 'Does Akowe support footnotes?',
    answer: 'Yes, Akowe supports footnotes for citation styles that use them, such as Chicago Notes-Bibliography style. Footnotes are automatically formatted and numbered.',
    keywords: ['akowe footnotes', 'akowe chicago style', 'akowe notes'],
  },
  {
    slug: 'can-i-export-my-bibliography-from-akowe',
    question: 'Can I export my bibliography from Akowe?',
    answer: 'Yes, when you export your paper, your bibliography is included and automatically formatted. You can also copy your bibliography separately if needed.',
    keywords: ['akowe bibliography', 'akowe export bibliography', 'akowe references'],
  },
  {
    slug: 'how-accurate-is-akowe-plagiarism-checker',
    question: 'How accurate is Akowe\'s plagiarism checker?',
    answer: 'Akowe\'s plagiarism checker uses advanced algorithms to detect potential plagiarism. It compares your work against a comprehensive database and provides detailed similarity reports.',
    keywords: ['akowe plagiarism accuracy', 'akowe plagiarism detection', 'akowe similarity check'],
  },
  {
    slug: 'does-akowe-store-my-plagiarism-reports',
    question: 'Does Akowe store my plagiarism reports?',
    answer: 'Plagiarism reports are stored securely with your project. You can access them anytime from your project. Reports are private and only visible to you.',
    keywords: ['akowe plagiarism reports', 'akowe plagiarism storage', 'akowe privacy'],
  },
  {
    slug: 'can-i-check-plagiarism-before-submitting',
    question: 'Can I check for plagiarism before submitting?',
    answer: 'Yes, you can check your paper for plagiarism at any time during the writing process. This helps you catch and fix issues before final submission.',
    keywords: ['akowe plagiarism check', 'akowe before submission', 'akowe plagiarism prevention'],
  },
  {
    slug: 'what-sources-does-akowe-plagiarism-checker-compare-against',
    question: 'What sources does Akowe\'s plagiarism checker compare against?',
    answer: 'Akowe\'s plagiarism checker compares your work against academic databases, published papers, web content, and other sources to identify potential matches.',
    keywords: ['akowe plagiarism database', 'akowe plagiarism sources', 'akowe similarity detection'],
  },
  {
    slug: 'how-do-i-improve-my-akowe-plagiarism-score',
    question: 'How do I improve my Akowe plagiarism score?',
    answer: 'To improve your plagiarism score, ensure all sources are properly cited, paraphrase effectively, use your own words, and add original analysis. Akowe helps you cite sources correctly.',
    keywords: ['akowe plagiarism score', 'akowe reduce plagiarism', 'akowe academic integrity'],
  },
  {
    slug: 'does-akowe-support-apa-7th-edition',
    question: 'Does Akowe support APA 7th edition?',
    answer: 'Yes, Akowe fully supports APA 7th edition formatting. All citations and references are automatically formatted according to the latest APA guidelines.',
    keywords: ['akowe APA 7', 'akowe APA 7th edition', 'akowe APA format'],
  },
  {
    slug: 'does-akowe-support-mla-9th-edition',
    question: 'Does Akowe support MLA 9th edition?',
    answer: 'Yes, Akowe fully supports MLA 9th edition formatting. All citations and Works Cited entries are automatically formatted according to the latest MLA guidelines.',
    keywords: ['akowe MLA 9', 'akowe MLA 9th edition', 'akowe MLA format'],
  },
  {
    slug: 'can-i-switch-citation-styles-in-akowe',
    question: 'Can I switch citation styles in Akowe?',
    answer: 'Yes, you can change citation styles at any time in your project settings. Akowe will automatically reformat all your citations and bibliography to the new style.',
    keywords: ['akowe change citation style', 'akowe switch styles', 'akowe citation format'],
  },
  {
    slug: 'how-do-i-add-a-citation-in-akowe',
    question: 'How do I add a citation in Akowe?',
    answer: 'To add a citation, use the citation search feature to find your source, select it, and choose where to insert it in your paper. Akowe automatically formats it correctly.',
    keywords: ['akowe add citation', 'akowe insert citation', 'akowe cite source'],
  },
  {
    slug: 'can-i-edit-citations-in-akowe',
    question: 'Can I edit citations in Akowe?',
    answer: 'Yes, you can edit citation information if needed. Akowe allows you to modify citation details while maintaining proper formatting.',
    keywords: ['akowe edit citation', 'akowe modify citation', 'akowe citation editing'],
  },
  {
    slug: 'how-do-i-remove-a-citation-from-akowe',
    question: 'How do I remove a citation from Akowe?',
    answer: 'You can remove citations directly from your paper. When you delete a citation, Akowe automatically updates your bibliography.',
    keywords: ['akowe remove citation', 'akowe delete citation', 'akowe citation removal'],
  },
  {
    slug: 'does-akowe-support-in-text-citations',
    question: 'Does Akowe support in-text citations?',
    answer: 'Yes, Akowe automatically formats in-text citations according to your chosen citation style. Citations are inserted where you place them in your text.',
    keywords: ['akowe in-text citations', 'akowe parenthetical citations', 'akowe citation format'],
  },
  {
    slug: 'can-i-cite-sources-not-in-akowe-database',
    question: 'Can I cite sources not in Akowe\'s database?',
    answer: 'Yes, you can manually add citation information for sources not found in Akowe\'s database. Akowe will format them correctly according to your citation style.',
    keywords: ['akowe manual citation', 'akowe add source', 'akowe custom citation'],
  },
  {
    slug: 'how-do-i-find-sources-in-akowe',
    question: 'How do I find sources in Akowe?',
    answer: 'Use Akowe\'s citation search to find sources from OpenAlex and Crossref databases. You can search by title, author, DOI, or keywords.',
    keywords: ['akowe find sources', 'akowe source search', 'akowe search citations'],
  },
  {
    slug: 'does-akowe-support-doi-citations',
    question: 'Does Akowe support DOI citations?',
    answer: 'Yes, Akowe can search for sources by DOI and automatically format citations with DOI information according to your citation style requirements.',
    keywords: ['akowe DOI', 'akowe digital object identifier', 'akowe DOI citation'],
  },
  {
    slug: 'can-i-save-sources-for-later-in-akowe',
    question: 'Can I save sources for later in Akowe?',
    answer: 'Yes, sources you add to your project are saved in your bibliography. You can reuse them throughout your paper and access them anytime.',
    keywords: ['akowe save sources', 'akowe source library', 'akowe bibliography'],
  },
  {
    slug: 'how-do-i-organize-sources-in-akowe',
    question: 'How do I organize sources in Akowe?',
    answer: 'Sources are automatically organized in your bibliography. You can view all sources, search them, and manage them from your project\'s citation section.',
    keywords: ['akowe organize sources', 'akowe source management', 'akowe bibliography organization'],
  },
  {
    slug: 'does-akowe-support-multiple-projects',
    question: 'Does Akowe support multiple projects?',
    answer: 'Yes, you can create and manage multiple projects in Akowe. Each project has its own sources, citations, and settings. Switch between projects easily.',
    keywords: ['akowe multiple projects', 'akowe projects', 'akowe workspace'],
  },
  {
    slug: 'how-do-i-rename-a-project-in-akowe',
    question: 'How do I rename a project in Akowe?',
    answer: 'You can rename your project from the project settings. Click on the project name and edit it directly, or use the settings menu.',
    keywords: ['akowe rename project', 'akowe project settings', 'akowe project management'],
  },
  {
    slug: 'can-i-duplicate-a-project-in-akowe',
    question: 'Can I duplicate a project in Akowe?',
    answer: 'Currently, you can create a new project and copy content manually. Project duplication features are planned for future updates.',
    keywords: ['akowe duplicate project', 'akowe copy project', 'akowe project template'],
  },
  {
    slug: 'how-do-i-delete-a-project-in-akowe',
    question: 'How do I delete a project in Akowe?',
    answer: 'You can delete a project from the project settings. This action is permanent, so make sure to export any work you want to keep before deleting.',
    keywords: ['akowe delete project', 'akowe remove project', 'akowe project deletion'],
  },
  {
    slug: 'does-akowe-have-version-history',
    question: 'Does Akowe have version history?',
    answer: 'Akowe automatically saves your work as you write. Full version history with the ability to restore previous versions is planned for future updates.',
    keywords: ['akowe version history', 'akowe revisions', 'akowe document history'],
  },
  {
    slug: 'can-i-export-my-akowe-project-to-word',
    question: 'Can I export my Akowe project to Word?',
    answer: 'Yes, you can export your project to Word (.docx) format. Your citations and bibliography are automatically formatted and included in the export.',
    keywords: ['akowe export word', 'akowe word export', 'akowe docx export'],
  },
  {
    slug: 'can-i-export-my-akowe-project-to-pdf',
    question: 'Can I export my Akowe project to PDF?',
    answer: 'Yes, you can export your project to PDF format. Your citations, bibliography, and formatting are preserved in the PDF export.',
    keywords: ['akowe export pdf', 'akowe pdf export', 'akowe pdf download'],
  },
  {
    slug: 'does-akowe-support-latex-export',
    question: 'Does Akowe support LaTeX export?',
    answer: 'Yes, Akowe supports LaTeX export. You can export your project in LaTeX format with properly formatted citations and bibliography.',
    keywords: ['akowe latex export', 'akowe latex', 'akowe tex export'],
  },
  {
    slug: 'how-do-i-print-my-akowe-project',
    question: 'How do I print my Akowe project?',
    answer: 'You can export your project to PDF and print it, or use your browser\'s print function. Akowe\'s formatting is preserved for printing.',
    keywords: ['akowe print', 'akowe printing', 'akowe print project'],
  },
];

export function getFAQBySlug(slug: string): FAQ | undefined {
  return faqs.find(faq => faq.slug === slug);
}

export function getAllFAQSlugs(): string[] {
  return faqs.map(faq => faq.slug);
}

