// Template data for programmatic SEO pages
export interface Template {
  slug: string;
  title: string;
  description: string;
  keywords: string[];
  type: string;
  useCase: string;
  structure: string[];
}

export const templates: Template[] = [
  {
    slug: 'research-paper',
    title: 'Research Paper Template: Structure and Format Guide',
    description: 'Free research paper template with proper structure, formatting guidelines, and section organization. Download and customize for your academic paper.',
    keywords: [
      'research paper template',
      'academic paper template',
      'research paper format',
      'research paper structure',
      'research paper outline',
    ],
    type: 'Research Paper',
    useCase: 'Standard academic research papers, term papers, and course assignments',
    structure: [
      'Title Page',
      'Abstract',
      'Introduction',
      'Literature Review',
      'Methodology',
      'Results',
      'Discussion',
      'Conclusion',
      'References',
    ],
  },
  {
    slug: 'thesis',
    title: 'Thesis Template: Complete Structure for Your Dissertation',
    description: 'Comprehensive thesis template with all required sections, formatting guidelines, and organization tips. Perfect for master\'s and doctoral theses.',
    keywords: [
      'thesis template',
      'dissertation template',
      'thesis structure',
      'thesis format',
      'thesis outline',
    ],
    type: 'Thesis/Dissertation',
    useCase: 'Master\'s theses, doctoral dissertations, and extended research projects',
    structure: [
      'Title Page',
      'Abstract',
      'Table of Contents',
      'List of Figures/Tables',
      'Introduction',
      'Literature Review',
      'Methodology',
      'Results',
      'Discussion',
      'Conclusion',
      'References',
      'Appendices',
    ],
  },
  {
    slug: 'essay',
    title: 'Academic Essay Template: Structure and Writing Guide',
    description: 'Academic essay template with introduction, body paragraphs, and conclusion structure. Perfect for college and university essays.',
    keywords: [
      'essay template',
      'academic essay template',
      'essay structure',
      'essay format',
      'college essay template',
    ],
    type: 'Essay',
    useCase: 'College essays, argumentative essays, analytical essays, and course assignments',
    structure: [
      'Introduction (with thesis statement)',
      'Body Paragraph 1',
      'Body Paragraph 2',
      'Body Paragraph 3',
      'Conclusion',
      'Works Cited/References',
    ],
  },
  {
    slug: 'literature-review',
    title: 'Literature Review Template: Structure and Organization Guide',
    description: 'Literature review template with thematic organization, synthesis strategies, and citation guidelines. Perfect for research papers and theses.',
    keywords: [
      'literature review template',
      'literature review structure',
      'literature review format',
      'how to organize literature review',
    ],
    type: 'Literature Review',
    useCase: 'Standalone literature reviews or sections within research papers and theses',
    structure: [
      'Introduction',
      'Thematic Section 1',
      'Thematic Section 2',
      'Thematic Section 3',
      'Gap Analysis',
      'Conclusion',
      'References',
    ],
  },
  {
    slug: 'lab-report',
    title: 'Lab Report Template: Structure and Format Guide',
    description: 'Complete lab report template with proper structure for scientific experiments. Includes methodology, results, and analysis sections.',
    keywords: [
      'lab report template',
      'laboratory report template',
      'lab report format',
      'scientific report template',
      'experiment report template',
    ],
    type: 'Lab Report',
    useCase: 'Scientific experiments, laboratory assignments, and experimental research reports',
    structure: [
      'Title',
      'Abstract',
      'Introduction',
      'Materials and Methods',
      'Results',
      'Discussion',
      'Conclusion',
      'References',
      'Appendices',
    ],
  },
  {
    slug: 'case-study',
    title: 'Case Study Template: Structure and Organization Guide',
    description: 'Comprehensive case study template with sections for case description, analysis, and conclusions. Perfect for business and social science research.',
    keywords: [
      'case study template',
      'case study format',
      'case study structure',
      'case study example',
      'case study report template',
    ],
    type: 'Case Study',
    useCase: 'Business case studies, social science research, and in-depth analysis of specific instances',
    structure: [
      'Introduction',
      'Case Background',
      'Case Description',
      'Analysis',
      'Discussion',
      'Conclusions',
      'Recommendations',
      'References',
    ],
  },
  {
    slug: 'annotated-bibliography',
    title: 'Annotated Bibliography Template: Format and Structure',
    description: 'Annotated bibliography template with proper citation format and annotation structure. Perfect for research projects and literature reviews.',
    keywords: [
      'annotated bibliography template',
      'annotated bibliography format',
      'bibliography template',
      'annotated bibliography example',
      'research bibliography template',
    ],
    type: 'Annotated Bibliography',
    useCase: 'Research projects, literature reviews, and academic assignments requiring source summaries',
    structure: [
      'Title Page',
      'Introduction (optional)',
      'Annotated Entries (alphabetical)',
      'Each Entry: Citation + Summary + Evaluation',
    ],
  },
  {
    slug: 'research-proposal',
    title: 'Research Proposal Template: Complete Structure Guide',
    description: 'Comprehensive research proposal template with all required sections. Perfect for thesis proposals, grant applications, and research planning.',
    keywords: [
      'research proposal template',
      'thesis proposal template',
      'grant proposal template',
      'research proposal format',
      'proposal structure',
    ],
    type: 'Research Proposal',
    useCase: 'Thesis proposals, grant applications, and research project planning',
    structure: [
      'Title Page',
      'Abstract',
      'Introduction',
      'Literature Review',
      'Research Questions/Objectives',
      'Methodology',
      'Timeline',
      'Budget (if required)',
      'Expected Outcomes',
      'References',
    ],
  },
  {
    slug: 'systematic-review',
    title: 'Systematic Review Template: PRISMA Guidelines Structure',
    description: 'Systematic review template following PRISMA guidelines. Includes search strategy, screening, and synthesis sections.',
    keywords: [
      'systematic review template',
      'PRISMA template',
      'systematic review format',
      'meta-analysis template',
      'evidence synthesis template',
    ],
    type: 'Systematic Review',
    useCase: 'Evidence synthesis, systematic literature reviews, and meta-analyses',
    structure: [
      'Title',
      'Abstract',
      'Introduction',
      'Methods (Search Strategy, Screening, Quality Assessment)',
      'Results (PRISMA Flow Diagram, Study Characteristics)',
      'Discussion',
      'Conclusions',
      'References',
    ],
  },
  {
    slug: 'qualitative-research',
    title: 'Qualitative Research Paper Template: Structure Guide',
    description: 'Qualitative research paper template with sections for methodology, data collection, analysis, and findings presentation.',
    keywords: [
      'qualitative research template',
      'qualitative paper template',
      'qualitative study format',
      'qualitative research structure',
      'qualitative methodology template',
    ],
    type: 'Qualitative Research',
    useCase: 'Qualitative studies, interviews, focus groups, and ethnographic research',
    structure: [
      'Introduction',
      'Literature Review',
      'Methodology (Research Design, Data Collection, Analysis)',
      'Findings',
      'Discussion',
      'Conclusions',
      'References',
    ],
  },
  {
    slug: 'quantitative-research',
    title: 'Quantitative Research Paper Template: Structure Guide',
    description: 'Quantitative research paper template with sections for hypotheses, methodology, statistical analysis, and results presentation.',
    keywords: [
      'quantitative research template',
      'quantitative paper template',
      'statistical research template',
      'quantitative study format',
      'experimental research template',
    ],
    type: 'Quantitative Research',
    useCase: 'Experimental studies, surveys, statistical analysis, and quantitative research',
    structure: [
      'Introduction',
      'Literature Review',
      'Hypotheses',
      'Methodology',
      'Results',
      'Discussion',
      'Conclusions',
      'References',
    ],
  },
  {
    slug: 'mixed-methods',
    title: 'Mixed Methods Research Template: Structure Guide',
    description: 'Mixed methods research template combining qualitative and quantitative approaches. Includes integration strategies and reporting guidelines.',
    keywords: [
      'mixed methods template',
      'mixed methods research template',
      'qualitative quantitative template',
      'mixed methods format',
      'mixed methods study template',
    ],
    type: 'Mixed Methods Research',
    useCase: 'Research combining qualitative and quantitative methods',
    structure: [
      'Introduction',
      'Literature Review',
      'Research Design',
      'Qualitative Methods',
      'Quantitative Methods',
      'Integration Strategy',
      'Qualitative Results',
      'Quantitative Results',
      'Integrated Findings',
      'Discussion',
      'Conclusions',
      'References',
    ],
  },
  {
    slug: 'book-review',
    title: 'Book Review Template: Academic Book Review Structure',
    description: 'Academic book review template with sections for summary, analysis, and evaluation. Perfect for literature courses and academic assignments.',
    keywords: [
      'book review template',
      'academic book review',
      'book review format',
      'literature review book',
      'book analysis template',
    ],
    type: 'Book Review',
    useCase: 'Academic book reviews, literature course assignments, and scholarly book critiques',
    structure: [
      'Introduction (Book Info, Author, Context)',
      'Summary',
      'Analysis',
      'Evaluation',
      'Conclusion',
      'References',
    ],
  },
  {
    slug: 'article-review',
    title: 'Article Review Template: Academic Article Critique Structure',
    description: 'Academic article review template for critiquing research articles. Includes summary, analysis, and evaluation sections.',
    keywords: [
      'article review template',
      'article critique template',
      'journal article review',
      'article analysis template',
      'research article review',
    ],
    type: 'Article Review',
    useCase: 'Journal article critiques, research article reviews, and academic assignments',
    structure: [
      'Introduction (Article Info, Authors, Context)',
      'Summary',
      'Critical Analysis',
      'Evaluation',
      'Conclusion',
      'References',
    ],
  },
  {
    slug: 'reflection-paper',
    title: 'Reflection Paper Template: Structure and Format Guide',
    description: 'Reflection paper template for personal reflection on experiences, readings, or learning. Includes structure for reflective writing.',
    keywords: [
      'reflection paper template',
      'reflective essay template',
      'reflection paper format',
      'reflective writing template',
      'personal reflection template',
    ],
    type: 'Reflection Paper',
    useCase: 'Personal reflections, learning reflections, and reflective academic writing',
    structure: [
      'Introduction',
      'Description of Experience/Reading',
      'Analysis and Reflection',
      'Connection to Learning',
      'Conclusion',
    ],
  },
  {
    slug: 'position-paper',
    title: 'Position Paper Template: Argument and Structure Guide',
    description: 'Position paper template for presenting and defending a position on an issue. Includes argument structure and evidence presentation.',
    keywords: [
      'position paper template',
      'position paper format',
      'argumentative position paper',
      'policy position paper',
      'position statement template',
    ],
    type: 'Position Paper',
    useCase: 'Policy positions, argumentative papers, and position statements',
    structure: [
      'Introduction (Position Statement)',
      'Background',
      'Arguments Supporting Position',
      'Counterarguments and Rebuttals',
      'Conclusion',
      'References',
    ],
  },
  {
    slug: 'white-paper',
    title: 'White Paper Template: Research and Analysis Structure',
    description: 'White paper template for in-depth research and analysis on a topic. Includes problem definition, analysis, and recommendations.',
    keywords: [
      'white paper template',
      'white paper format',
      'research white paper',
      'analytical white paper',
      'white paper structure',
    ],
    type: 'White Paper',
    useCase: 'In-depth research reports, analytical papers, and comprehensive topic analysis',
    structure: [
      'Executive Summary',
      'Introduction',
      'Problem Statement',
      'Background Research',
      'Analysis',
      'Solutions/Recommendations',
      'Conclusion',
      'References',
    ],
  },
  {
    slug: 'policy-brief',
    title: 'Policy Brief Template: Structure and Format Guide',
    description: 'Policy brief template for presenting research findings to policymakers. Includes concise structure and actionable recommendations.',
    keywords: [
      'policy brief template',
      'policy brief format',
      'policy paper template',
      'policy analysis template',
      'briefing paper template',
    ],
    type: 'Policy Brief',
    useCase: 'Policy recommendations, briefing papers, and policy analysis',
    structure: [
      'Title',
      'Executive Summary',
      'Problem Statement',
      'Background',
      'Policy Options',
      'Recommendations',
      'References',
    ],
  },
  {
    slug: 'grant-proposal',
    title: 'Grant Proposal Template: Complete Structure Guide',
    description: 'Grant proposal template with all required sections for funding applications. Includes budget, timeline, and impact sections.',
    keywords: [
      'grant proposal template',
      'funding proposal template',
      'research grant template',
      'grant application format',
      'proposal writing template',
    ],
    type: 'Grant Proposal',
    useCase: 'Research funding applications, grant proposals, and funding requests',
    structure: [
      'Cover Page',
      'Abstract/Summary',
      'Introduction',
      'Problem Statement',
      'Objectives',
      'Methodology',
      'Timeline',
      'Budget',
      'Expected Outcomes',
      'Impact Statement',
      'References',
    ],
  },
  {
    slug: 'dissertation-proposal',
    title: 'Dissertation Proposal Template: Complete Structure',
    description: 'Dissertation proposal template with all required sections for PhD and master\'s thesis proposals. Includes comprehensive methodology and timeline.',
    keywords: [
      'dissertation proposal template',
      'thesis proposal template',
      'PhD proposal template',
      'dissertation proposal format',
      'thesis proposal structure',
    ],
    type: 'Dissertation Proposal',
    useCase: 'PhD and master\'s thesis proposals, doctoral research proposals',
    structure: [
      'Title Page',
      'Abstract',
      'Introduction',
      'Literature Review',
      'Research Questions',
      'Methodology',
      'Expected Outcomes',
      'Timeline',
      'Resources Required',
      'References',
    ],
  },
  {
    slug: 'conference-paper',
    title: 'Conference Paper Template: Structure and Format Guide',
    description: 'Conference paper template for academic conferences. Includes concise structure and presentation guidelines.',
    keywords: [
      'conference paper template',
      'conference presentation template',
      'academic conference paper',
      'conference paper format',
      'conference presentation format',
    ],
    type: 'Conference Paper',
    useCase: 'Academic conference presentations, conference proceedings, and conference submissions',
    structure: [
      'Title',
      'Abstract',
      'Introduction',
      'Methodology',
      'Results',
      'Discussion',
      'Conclusions',
      'References',
    ],
  },
  {
    slug: 'journal-article',
    title: 'Journal Article Template: Academic Journal Format',
    description: 'Journal article template following standard academic journal structure. Includes IMRaD format and journal-specific requirements.',
    keywords: [
      'journal article template',
      'academic journal template',
      'journal paper format',
      'research article template',
      'IMRaD template',
    ],
    type: 'Journal Article',
    useCase: 'Academic journal submissions, research articles, and peer-reviewed publications',
    structure: [
      'Title',
      'Abstract',
      'Keywords',
      'Introduction',
      'Methods',
      'Results',
      'Discussion',
      'Conclusions',
      'Acknowledgments',
      'References',
    ],
  },
  {
    slug: 'technical-report',
    title: 'Technical Report Template: Structure and Format Guide',
    description: 'Technical report template for engineering, science, and technology reports. Includes methodology, results, and technical analysis sections.',
    keywords: [
      'technical report template',
      'engineering report template',
      'scientific report template',
      'technical report format',
      'engineering paper template',
    ],
    type: 'Technical Report',
    useCase: 'Engineering reports, scientific technical reports, and technology documentation',
    structure: [
      'Title Page',
      'Executive Summary',
      'Table of Contents',
      'Introduction',
      'Methodology',
      'Results',
      'Analysis',
      'Conclusions',
      'Recommendations',
      'Appendices',
      'References',
    ],
  },
  {
    slug: 'grant-proposal-template',
    title: 'Grant Proposal Template - Free Download',
    description: 'Free grant proposal template for research funding applications. Includes sections for objectives, methodology, budget, and timeline.',
    keywords: ['grant proposal template', 'research grant template', 'funding proposal', 'grant application template'],
    type: 'Grant Proposal',
    useCase: 'Research funding applications, grant proposals, and funding requests',
    structure: ['Cover Page', 'Executive Summary', 'Objectives', 'Methodology', 'Budget', 'Timeline', 'References'],
  },
  {
    slug: 'research-proposal-template',
    title: 'Research Proposal Template - Academic Format',
    description: 'Free research proposal template for academic research projects. Includes introduction, literature review, methodology, and timeline sections.',
    keywords: ['research proposal template', 'academic proposal template', 'research plan template', 'proposal format'],
    type: 'Research Proposal',
    useCase: 'Academic research proposals, thesis proposals, and research plans',
    structure: ['Title', 'Abstract', 'Introduction', 'Literature Review', 'Methodology', 'Timeline', 'References'],
  },
  {
    slug: 'dissertation-proposal-template',
    title: 'Dissertation Proposal Template - PhD Format',
    description: 'Free dissertation proposal template for PhD students. Includes problem statement, objectives, methodology, and expected outcomes.',
    keywords: ['dissertation proposal template', 'PhD proposal template', 'doctoral proposal', 'dissertation plan'],
    type: 'Dissertation Proposal',
    useCase: 'PhD dissertation proposals and doctoral research plans',
    structure: ['Title', 'Abstract', 'Problem Statement', 'Objectives', 'Literature Review', 'Methodology', 'Expected Outcomes', 'Timeline', 'References'],
  },
  {
    slug: 'thesis-proposal-template',
    title: 'Thesis Proposal Template - Master\'s Format',
    description: 'Free thesis proposal template for master\'s students. Includes research question, literature review, methodology, and timeline.',
    keywords: ['thesis proposal template', 'master\'s proposal template', 'thesis plan', 'research proposal'],
    type: 'Thesis Proposal',
    useCase: 'Master\'s thesis proposals and graduate research plans',
    structure: ['Title', 'Research Question', 'Literature Review', 'Methodology', 'Timeline', 'References'],
  },
  {
    slug: 'annotated-bibliography-template',
    title: 'Annotated Bibliography Template - Academic Format',
    description: 'Free annotated bibliography template with proper formatting. Includes citation and annotation sections for each source.',
    keywords: ['annotated bibliography template', 'bibliography template', 'citation template', 'annotated bib template'],
    type: 'Annotated Bibliography',
    useCase: 'Research projects requiring source summaries and evaluations',
    structure: ['Citation', 'Summary', 'Evaluation', 'Reflection'],
  },
  {
    slug: 'research-paper-outline-template',
    title: 'Research Paper Outline Template - Structured Format',
    description: 'Free research paper outline template to organize your research. Includes sections for introduction, body, and conclusion.',
    keywords: ['research paper outline', 'paper outline template', 'research outline', 'academic outline'],
    type: 'Outline',
    useCase: 'Organizing research papers before writing',
    structure: ['Introduction', 'Body Paragraphs', 'Conclusion'],
  },
  {
    slug: 'thesis-outline-template',
    title: 'Thesis Outline Template - Complete Structure',
    description: 'Free thesis outline template with all standard sections. Includes chapters, subheadings, and organization guidelines.',
    keywords: ['thesis outline template', 'dissertation outline', 'thesis structure', 'thesis organization'],
    type: 'Thesis Outline',
    useCase: 'Organizing thesis and dissertation structure',
    structure: ['Chapters', 'Subheadings', 'Sections'],
  },
  {
    slug: 'abstract-template',
    title: 'Abstract Template - Research Paper Format',
    description: 'Free abstract template for research papers. Includes guidelines for writing effective abstracts in APA, MLA, and other styles.',
    keywords: ['abstract template', 'research abstract template', 'paper abstract', 'abstract format'],
    type: 'Abstract',
    useCase: 'Research papers, theses, and conference submissions',
    structure: ['Background', 'Objective', 'Methods', 'Results', 'Conclusion'],
  },
  {
    slug: 'executive-summary-template',
    title: 'Executive Summary Template - Business Format',
    description: 'Free executive summary template for business reports and proposals. Includes key points, findings, and recommendations sections.',
    keywords: ['executive summary template', 'summary template', 'business summary', 'report summary'],
    type: 'Executive Summary',
    useCase: 'Business reports, proposals, and executive briefings',
    structure: ['Key Points', 'Findings', 'Recommendations'],
  },
  {
    slug: 'methodology-template',
    title: 'Methodology Template - Research Format',
    description: 'Free methodology template for research papers. Includes sections for research design, data collection, and analysis methods.',
    keywords: ['methodology template', 'research methodology template', 'methods template', 'methodology section'],
    type: 'Methodology',
    useCase: 'Research papers requiring detailed methodology sections',
    structure: ['Research Design', 'Data Collection', 'Analysis Methods'],
  },
  {
    slug: 'results-section-template',
    title: 'Results Section Template - Data Presentation',
    description: 'Free results section template for research papers. Includes guidelines for presenting data, tables, and figures.',
    keywords: ['results template', 'results section template', 'data presentation template', 'research results'],
    type: 'Results',
    useCase: 'Research papers presenting experimental or survey data',
    structure: ['Data Presentation', 'Tables', 'Figures', 'Statistical Analysis'],
  },
  {
    slug: 'discussion-section-template',
    title: 'Discussion Section Template - Analysis Format',
    description: 'Free discussion section template for research papers. Includes interpretation, implications, and limitations sections.',
    keywords: ['discussion template', 'discussion section template', 'analysis template', 'research discussion'],
    type: 'Discussion',
    useCase: 'Research papers requiring interpretation and analysis',
    structure: ['Interpretation', 'Implications', 'Limitations', 'Future Research'],
  },
  {
    slug: 'conclusion-template',
    title: 'Conclusion Template - Research Paper Format',
    description: 'Free conclusion template for research papers. Includes summary, implications, and future research directions.',
    keywords: ['conclusion template', 'research conclusion template', 'paper conclusion', 'conclusion format'],
    type: 'Conclusion',
    useCase: 'Research papers, theses, and academic documents',
    structure: ['Summary', 'Implications', 'Future Directions'],
  },
  {
    slug: 'introduction-template',
    title: 'Introduction Template - Research Paper Format',
    description: 'Free introduction template for research papers. Includes hook, background, research question, and thesis statement sections.',
    keywords: ['introduction template', 'research introduction template', 'paper introduction', 'introduction format'],
    type: 'Introduction',
    useCase: 'Research papers, essays, and academic documents',
    structure: ['Hook', 'Background', 'Research Question', 'Thesis Statement'],
  },
  {
    slug: 'literature-review-template',
    title: 'Literature Review Template - Academic Format',
    description: 'Free literature review template for research papers and theses. Includes organization, synthesis, and citation guidelines.',
    keywords: ['literature review template', 'lit review template', 'literature review format', 'review template'],
    type: 'Literature Review',
    useCase: 'Research papers, theses, and systematic reviews',
    structure: ['Introduction', 'Thematic Organization', 'Synthesis', 'Conclusion'],
  },
  {
    slug: 'research-log-template',
    title: 'Research Log Template - Note-Taking Format',
    description: 'Free research log template for tracking sources and notes. Includes citation information, summaries, and analysis sections.',
    keywords: ['research log template', 'research notes template', 'source log', 'research tracking'],
    type: 'Research Log',
    useCase: 'Tracking sources and notes during research',
    structure: ['Citation', 'Summary', 'Analysis', 'Notes'],
  },
  {
    slug: 'data-analysis-template',
    title: 'Data Analysis Template - Statistical Format',
    description: 'Free data analysis template for research papers. Includes sections for descriptive statistics, inferential statistics, and interpretation.',
    keywords: ['data analysis template', 'statistical analysis template', 'analysis format', 'data template'],
    type: 'Data Analysis',
    useCase: 'Research papers with statistical analysis',
    structure: ['Descriptive Statistics', 'Inferential Statistics', 'Interpretation'],
  },
  {
    slug: 'qualitative-research-template',
    title: 'Qualitative Research Template - Analysis Format',
    description: 'Free qualitative research template for qualitative studies. Includes thematic analysis, coding, and interpretation sections.',
    keywords: ['qualitative research template', 'qualitative analysis template', 'qualitative study template', 'qualitative format'],
    type: 'Qualitative Research',
    useCase: 'Qualitative research studies and analysis',
    structure: ['Data Collection', 'Thematic Analysis', 'Coding', 'Interpretation'],
  },
  {
    slug: 'quantitative-research-template',
    title: 'Quantitative Research Template - Statistical Format',
    description: 'Free quantitative research template for quantitative studies. Includes hypothesis, variables, statistical tests, and results sections.',
    keywords: ['quantitative research template', 'quantitative analysis template', 'statistical research template', 'quantitative format'],
    type: 'Quantitative Research',
    useCase: 'Quantitative research studies and statistical analysis',
    structure: ['Hypothesis', 'Variables', 'Statistical Tests', 'Results'],
  },
  {
    slug: 'mixed-methods-template',
    title: 'Mixed Methods Research Template - Combined Format',
    description: 'Free mixed methods research template combining qualitative and quantitative approaches. Includes integration and analysis sections.',
    keywords: ['mixed methods template', 'mixed methods research template', 'combined methods template', 'mixed research format'],
    type: 'Mixed Methods',
    useCase: 'Research combining qualitative and quantitative methods',
    structure: ['Qualitative Component', 'Quantitative Component', 'Integration', 'Analysis'],
  },
  {
    slug: 'systematic-review-template',
    title: 'Systematic Review Template - PRISMA Format',
    description: 'Free systematic review template following PRISMA guidelines. Includes search strategy, screening, and synthesis sections.',
    keywords: ['systematic review template', 'PRISMA template', 'review template', 'systematic review format'],
    type: 'Systematic Review',
    useCase: 'Systematic reviews and evidence synthesis',
    structure: ['Search Strategy', 'Screening', 'Quality Assessment', 'Synthesis'],
  },
  {
    slug: 'meta-analysis-template',
    title: 'Meta-Analysis Template - Statistical Format',
    description: 'Free meta-analysis template for combining multiple studies. Includes effect size calculation, heterogeneity analysis, and forest plots.',
    keywords: ['meta-analysis template', 'meta analysis template', 'statistical synthesis template', 'meta-analysis format'],
    type: 'Meta-Analysis',
    useCase: 'Meta-analyses combining multiple studies',
    structure: ['Effect Size Calculation', 'Heterogeneity Analysis', 'Forest Plots', 'Interpretation'],
  },
  {
    slug: 'case-study-template',
    title: 'Case Study Template - Research Format',
    description: 'Free case study template for case study research. Includes case description, analysis, and discussion sections.',
    keywords: ['case study template', 'case study format', 'case study research template', 'case analysis template'],
    type: 'Case Study',
    useCase: 'Case study research and analysis',
    structure: ['Case Description', 'Context', 'Analysis', 'Discussion'],
  },
  {
    slug: 'ethnography-template',
    title: 'Ethnography Template - Qualitative Format',
    description: 'Free ethnography template for ethnographic research. Includes field notes, observations, and cultural analysis sections.',
    keywords: ['ethnography template', 'ethnographic research template', 'ethnography format', 'fieldwork template'],
    type: 'Ethnography',
    useCase: 'Ethnographic research and cultural analysis',
    structure: ['Field Notes', 'Observations', 'Cultural Analysis', 'Interpretation'],
  },
  {
    slug: 'survey-research-template',
    title: 'Survey Research Template - Questionnaire Format',
    description: 'Free survey research template for survey studies. Includes questionnaire design, sampling, and analysis sections.',
    keywords: ['survey template', 'survey research template', 'questionnaire template', 'survey format'],
    type: 'Survey Research',
    useCase: 'Survey research and questionnaire studies',
    structure: ['Questionnaire Design', 'Sampling', 'Data Collection', 'Analysis'],
  },
  {
    slug: 'experimental-research-template',
    title: 'Experimental Research Template - Scientific Format',
    description: 'Free experimental research template for experiments. Includes hypothesis, design, procedures, and results sections.',
    keywords: ['experimental template', 'experiment template', 'experimental research format', 'scientific experiment template'],
    type: 'Experimental Research',
    useCase: 'Experimental research and scientific studies',
    structure: ['Hypothesis', 'Design', 'Procedures', 'Results'],
  },
];

export function getTemplateBySlug(slug: string): Template | undefined {
  return templates.find(template => template.slug === slug);
}

export function getAllTemplateSlugs(): string[] {
  return templates.map(template => template.slug);
}

